<a href="https://colab.research.google.com/github/shrutin567/Computational-Thinking-with-Python-Integrated-Lab/blob/main/ctpy_integrated_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Python program to evaluate Values, expressions, and statements, Conditional execution, and Functions
Iterations

a. prompt the user to enter an integer and reverse it. And print the sum of the reversed integer.

b. Write a python program to find whether a number (num1) is a factor of 255.

c.  Write a python program to find whether a number (num1) is a factor of 255.

d.    Write a program to find the sum of the following series:                                         
i.   1 + 1/3 + 1/5 + 1/7 + .... up to ‘N’ terms.                             
ii.  1 + x/1! + x3/2! + x5/3! + x7/4 + .... x2n-1/n!


In [1]:
import math

# Task a
def reverse_integer_and_sum():
    num = int(input("Enter an integer: "))
    reversed_num = int(str(num)[::-1])
    sum_reversed = num + reversed_num
    print(f"Reversed: {reversed_num}")
    print(f"Sum: {sum_reversed}")

reverse_integer_and_sum()

# Task b
def is_factor(num, factor):
    return factor != 0 and num % factor == 0

num1 = int(input("Enter a number: "))
if is_factor(255, num1):
    print(f"{num1} is a factor of 255")
else:
    print(f"{num1} is not a factor of 255")

# Task c
num2 = int(input("Enter another number: "))
if is_factor(255, num2):
    print(f"{num2} is a factor of 255")
else:
    print(f"{num2} is not a factor of 255")

# Task d i
def sum_series_term(n):
    return 1 / (2 * n - 1)

N = int(input("Enter the value of N: "))
series_sum = sum(sum_series_term(i) for i in range(1, N + 1))
print(f"Sum of the series: {series_sum}")

# Task d ii
def sum_series_term_2(x, n):
    return (x ** (2 * n - 1)) / math.factorial(n - 1)

x_value = float(input("Enter the value of x: "))
N_value = int(input("Enter the value of N: "))
series_sum_2 = sum(sum_series_term_2(x_value, i) for i in range(1, N_value + 1))
print(f"Sum of the series: {series_sum_2}")


Enter an integer: 56
Reversed: 65
Sum: 121
Enter a number: 34
34 is not a factor of 255
Enter another number: 7
7 is not a factor of 255
Enter the value of N: 3
Sum of the series: 1.5333333333333332
Enter the value of x: 3
Enter the value of N: 5
Sum of the series: 1336.125


2.  Python program to evaluate Python Collections

a.   Write a Python Program to demonstrate the inbuilt functions of Strings, List, and sets.

b.    Write a Python program for counting a specific letter 'o' in a given string; the number of times vowel
‘o’ appears.

c.    Write a Python Program to find the frequency of each word in given strings/strings

d.    Store the following for ‘n’ countries, using a dictionary:                            
i.  Name of a country, country’s capital, per capita income of the country.
                                      
ii.  Write a program to display details of the country with the highest and second lowest per capita income.2.  Python program to evaluate Python Collections

a.   Write a Python Program to demonstrate the inbuilt functions of Strings, List, and sets.

b.    Write a Python program for counting a specific letter 'o' in a given string; the number of times vowel
‘o’ appears.

c.    Write a Python Program to find the frequency of each word in given strings/strings

d.    Store the following for ‘n’ countries, using a dictionary:                            
i.  Name of a country, country’s capital, per capita income of the country.
                                      
ii.  Write a program to display details of the country with the highest and second lowest per capita income.

In [4]:
# Task a
# Strings
string_example = "Hello, this is a string example."
print("String length:", len(string_example))
print("Uppercase:", string_example.upper())
print("Lowercase:", string_example.lower())
print("Split:", string_example.split())

# Lists
list_example = [1, 2, 3, 4, 5]
print("List length:", len(list_example))
print("Sum:", sum(list_example))
print("Sorted:", sorted(list_example))
print("List with repetition:", list_example * 3)

# Sets
set_example = {1, 2, 3, 4, 5}
print("Set length:", len(set_example))
print("Union:", set_example.union({4, 5, 6}))
print("Intersection:", set_example.intersection({3, 4, 5}))
print("Is subset:", set_example.issubset({1, 2, 3, 4, 5, 6}))

# Task b
def count_letter_o(input_string):
    return input_string.lower().count('o')

user_input = input("Enter a string: ")
o_count = count_letter_o(user_input)
print(f"Number of 'o's in the string: {o_count}")

# Task c
def word_frequency(input_string):
    words = input_string.split()
    frequency = {}
    for word in words:
        frequency[word] = frequency.get(word, 0) + 1
    return frequency

user_input = input("Enter a string: ")
word_freq = word_frequency(user_input)
print("Word frequency:", word_freq)

# Task d
n = int(input("Enter the number of countries: "))
country_details = []

for _ in range(n):
    country_name = input("Enter country name: ")
    capital = input("Enter capital: ")
    per_capita_income = float(input("Enter per capita income: "))
    country_details.append({
        'country_name': country_name,
        'capital': capital,
        'per_capita_income': per_capita_income
    })

highest_income_country = max(country_details, key=lambda x: x['per_capita_income'])
second_lowest_income_country = min(sorted(country_details, key=lambda x: x['per_capita_income'])[1:], key=lambda x: x['per_capita_income'])

print("Details of the country with highest per capita income:")
print("Country:", highest_income_country['country_name'])
print("Capital:", highest_income_country['capital'])
print("Per Capita Income:", highest_income_country['per_capita_income'])

print("Details of the country with second lowest per capita income:")
print("Country:", second_lowest_income_country['country_name'])
print("Capital:", second_lowest_income_country['capital'])
print("Per Capita Income:", second_lowest_income_country['per_capita_income'])
c

String length: 32
Uppercase: HELLO, THIS IS A STRING EXAMPLE.
Lowercase: hello, this is a string example.
Split: ['Hello,', 'this', 'is', 'a', 'string', 'example.']
List length: 5
Sum: 15
Sorted: [1, 2, 3, 4, 5]
List with repetition: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Set length: 5
Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4, 5}
Is subset: True
Enter a string: cOsmology
Number of 'o's in the string: 3
Enter a string: this is a test, this is an example
Word frequency: {'this': 2, 'is': 2, 'a': 1, 'test,': 1, 'an': 1, 'example': 1}
Enter the number of countries: 3
Enter country name: c1
Enter capital: cap1
Enter per capita income: 10000
Enter country name: c2
Enter capital: cap2
Enter per capita income: 15000
Enter country name: c3
Enter capital: cap3
Enter per capita income: 8000
Details of the country with highest per capita income:
Country: c2
Capital: cap2
Per Capita Income: 15000.0
Details of the country with second lowest per capita income:
Country: c1
Capital: cap1
Pe

3.  Write a python program to create two classes “Python” and “Java” having data members “Version” and “name” and
a member function “display()”. With the help of the object, print the appropriate messages.

In [5]:
class Python:
    def __init__(self, version, name):
        self.version = version
        self.name = name

    def display(self):
        print(f"Language: {self.name}")
        print(f"Version: {self.version}")
        print("Python is known for its simplicity and readability.")

class Java:
    def __init__(self, version, name):
        self.version = version
        self.name = name

    def display(self):
        print(f"Language: {self.name}")
        print(f"Version: {self.version}")
        print("Java is known for its platform independence and strong typing.")

# Creating objects of the classes
python_obj = Python("3.9", "Python")
java_obj = Java("11", "Java")

# Displaying information using the display() method
print("Python Information:")
python_obj.display()
print("\nJava Information:")
java_obj.display()


Python Information:
Language: Python
Version: 3.9
Python is known for its simplicity and readability.

Java Information:
Language: Java
Version: 11
Java is known for its platform independence and strong typing.


4.  Create a class “Employee” with __init__ method to initialize data members: Name, Designation, Ph. No., and a
member function display(). Create an instance for the class and display the details of the employee

In [7]:
class Employee:
    def __init__(self, name, designation, phone_number):
        self.name = name
        self.designation = designation
        self.phone_number = phone_number

    def display(self):
        print("Employee Details:")
        print(f"Name: {self.name}")
        print(f"Designation: {self.designation}")
        print(f"Phone Number: {self.phone_number}")

# Creating an instance of the Employee class
employee = Employee("ABC XYZ", "Software Engineer", "123-456-7890")

# Displaying the details of the employee using the display() method
employee.display()


Employee Details:
Name: ABC XYZ
Designation: Software Engineer
Phone Number: 123-456-7890


5.  Write an interactive calculator. User input is assumed to be a formula that consist of a number, an operator
(at least + and -), and another number, separated by white space (e.g. 1 + 1). Split user input using str.split(), and check whether the resulting list is valid:

a.   If the input does not consist of 3 elements, raise a FormulaError, which is a custom Exception.

b.  Try to convert the first and third input to a float (like so: float_value = float(str_value)). Catch any ValueError that occurs, and instead raise a FormulaError

c.  If the second input is not '+' or '-', again raise a FormulaError

d.    If the input is valid, perform the calculation and print out the result. The user is then prompted to provide new input, and so on, until the user enters quit.

In [8]:
class FormulaError(Exception):
    pass

def perform_calculation(num1, operator, num2):
    if operator == '+':
        return num1 + num2
    elif operator == '-':
        return num1 - num2

def main():
    while True:
        user_input = input("Enter a formula (or 'quit' to exit): ")

        if user_input.lower() == 'quit':
            print("Exiting the calculator.")
            break

        try:
            elements = user_input.split()
            if len(elements) != 3:
                raise FormulaError("Invalid input: A formula should consist of 3 elements.")

            num1 = float(elements[0])
            num2 = float(elements[2])
            operator = elements[1]

            if operator not in ['+', '-']:
                raise FormulaError("Invalid operator: Only '+' and '-' operators are allowed.")

            result = perform_calculation(num1, operator, num2)
            print(f"Result: {result}")

        except ValueError:
            print("Error: Invalid number format.")
        except FormulaError as fe:
            print(f"Formula Error: {fe}")

if __name__ == "__main__":
    main()


Enter a formula (or 'quit' to exit): 5+3
Formula Error: Invalid input: A formula should consist of 3 elements.
Enter a formula (or 'quit' to exit): 5 + 3
Result: 8.0
Enter a formula (or 'quit' to exit): 4 * 2
Formula Error: Invalid operator: Only '+' and '-' operators are allowed.
Enter a formula (or 'quit' to exit): 10 - 2
Result: 8.0
Enter a formula (or 'quit' to exit): 7 / 2
Formula Error: Invalid operator: Only '+' and '-' operators are allowed.
Enter a formula (or 'quit' to exit): 3 +
Formula Error: Invalid input: A formula should consist of 3 elements.
Enter a formula (or 'quit' to exit): abc +
Formula Error: Invalid input: A formula should consist of 3 elements.
Enter a formula (or 'quit' to exit): abc+
Formula Error: Invalid input: A formula should consist of 3 elements.
Enter a formula (or 'quit' to exit): quit
Exiting the calculator.


6.  Write a Python program to count the number of lines in a text file and read the file line by line and store it into a list as well as find the longest word in the file.

In [11]:
def count_lines(file_path):
    with open(file_path, 'r') as file:
        line_count = sum(1 for line in file)
    return line_count

def read_file_and_store(file_path):
    lines = []
    with open(file_path, 'r') as file:
        for line in file:
            lines.append(line.strip())
    return lines

def find_longest_word(lines):
    longest_word = ''
    for line in lines:
        words = line.split()
        for word in words:
            if len(word) > len(longest_word):
                longest_word = word
    return longest_word

file_path = 'sample.txt'

line_count = count_lines(file_path)
print(f"Number of lines in the file: {line_count}")

lines_list = read_file_and_store(file_path)
print("Contents of the file stored in a list:")
for line in lines_list:
    print(line)

longest_word = find_longest_word(lines_list)
print(f"Longest word in the file: {longest_word}")


Number of lines in the file: 1
Contents of the file stored in a list:
hello world
Longest word in the file: hello


7. Write a Python program to create a list of student details: usn, name dob and email {using dictionary} and write a list to a file.


In [12]:
def write_student_details_to_file(student_list, file_path):
    with open(file_path, 'w') as file:
        for student in student_list:
            file.write(f"USN: {student['usn']}\n")
            file.write(f"Name: {student['name']}\n")
            file.write(f"DOB: {student['dob']}\n")
            file.write(f"Email: {student['email']}\n")
            file.write("\n")

def main():
    student_list = []

    n = int(input("Enter the number of students: "))
    for i in range(n):
        print(f"Enter details for student {i + 1}:")
        usn = input("USN: ")
        name = input("Name: ")
        dob = input("DOB: ")
        email = input("Email: ")
        student = {'usn': usn, 'name': name, 'dob': dob, 'email': email}
        student_list.append(student)
        print()

    file_path = 'sample.txt'
    write_student_details_to_file(student_list, file_path)
    print("Student details written to file successfully.")

if __name__ == "__main__":
    main()


Enter the number of students: 3
Enter details for student 1:
USN: 120
Name: abc
DOB: 2000-01-15
Email: abc@example.com

Enter details for student 2:
USN: 100
Name: xyz
DOB: 2001-05-17
Email: xyz@example.com

Enter details for student 3:
USN: def
Name: def
DOB: 2000-09-24
Email: def@example.com

Student details written to file successfully.


8.  Generate one-hot encodings for an array in numpy.


In [13]:
import numpy as np

# Define your input array with categorical values
input_array = np.array([0, 2, 1, 2, 0])

# Calculate the number of unique categories
num_categories = np.max(input_array) + 1

# Generate one-hot encodings using np.eye()
one_hot_encodings = np.eye(num_categories)[input_array]

print("Input array:")
print(input_array)

print("\nOne-hot encodings:")
print(one_hot_encodings)


Input array:
[0 2 1 2 0]

One-hot encodings:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


9.   Write a Pandas program to import excel data into a Pandas dataframe and find a list of employees where hire_date is between two specific month and year.

In [16]:
import pandas as pd

# Load Excel data into a Pandas DataFrame
file_path = 'employee_data.xlsx'
df = pd.read_excel(file_path)

# Convert 'hire_date' column to datetime
df['hire_date'] = pd.to_datetime(df['hire_date'])

# Define the start and end dates for filtering
start_date = pd.to_datetime('2020-01-01')
end_date = pd.to_datetime('2021-12-31')

# Filter employees based on hire_date
filtered_employees = df[(df['hire_date'] >= start_date) & (df['hire_date'] <= end_date)]

# Display the filtered employees
print("List of employees hired between Jan 2020 and Dec 2021:")
print(filtered_employees)



List of employees hired between Jan 2020 and Dec 2021:
   employee_id employee_name  hire_date
0            1           abc 2020-03-15
1            2           xyz 2021-08-10
